### ISSUE TITLE
Provide ability to decline topic application as a tech leader

### ISSUE THREAD

**Issue by sbunciak** [StudentHubCZ/studenthub-portal#62]

**Comment by sbunciak** [comment]
@TheSprtCz this is essentially a UI feature, isn't it? In terms of business logic it's simply grading a TopicApplication.

**Comment by TheSprtCz** [comment]
@sbunciak It depends what you want to do with that application afterwards, if you just want to delete it then it is just fine. If, on the other hand, you want to preserve it there could be some problems. One problem that since there is not field that differentiates waiting application and declined one, you can't tell which one is which.

**Comment by sbunciak** [comment]
@TheSprtCz I haven't thought of this, very good point. 
There are several possible solutions:

1) simply delete the application
2) add new field 'status'
3) add new grade to differentiate between graded F and declined

Since declined applications doesn't bring any value afaik, we could go with 1)
Wdyt?

**Comment by TheSprtCz** [comment]
Agree
